#!/bin/bash
# ============================================================
# WantokJobs - Master VPS Execution Script
# Run this as root on the VPS to complete ALL outstanding actions
# Generated by Agent Zero - 2026-03-19
# ============================================================

set -e
APP_DIR="/opt/wantokjobs/app"
ENV_FILE="$APP_DIR/.env"
LOG="/var/log/wantokjobs-agent-setup.log"

log() { echo "[$(date +'%H:%M:%S')] $*" | tee -a "$LOG"; }

log "====================================================="
log " WantokJobs Agent Zero - Complete Setup Run"
log "====================================================="

# ─── 1. Add agent SSH key ────────────────────────────────────
log "[1/9] Adding agent-zero SSH key..."
mkdir -p ~/.ssh
chmod 700 ~/.ssh
KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrhUYzK12LxJAj6lJmpiObxb2GFzTS/r+0VQeZb89N6 agent-zero-vps-2026"
if ! grep -q "agent-zero-vps-2026" ~/.ssh/authorized_keys 2>/dev/null; then
  echo "$KEY" >> ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
  log "   ✅ SSH key added"
else
  log "   ✅ SSH key already present"
fi

# ─── 2. Git pull latest code ─────────────────────────────────
log "[2/9] Pulling latest code from GitHub..."
cd "$APP_DIR"
git pull origin main 2>&1 | tee -a "$LOG"
log "   ✅ Code updated to: $(git log --oneline -1)"

# ─── 3. Stop duplicate WhatsApp service ──────────────────────
log "[3/9] Stopping duplicate jean-whatsapp service..."
if systemctl is-active --quiet jean-whatsapp 2>/dev/null; then
  systemctl stop jean-whatsapp
  systemctl disable jean-whatsapp
  log "   ✅ jean-whatsapp stopped and disabled"
elif systemctl list-unit-files 2>/dev/null | grep -q jean-whatsapp; then
  systemctl disable jean-whatsapp 2>/dev/null || true
  log "   ✅ jean-whatsapp disabled (was not running)"
else
  log "   ℹ️  jean-whatsapp service not found (OK - using webhook only)"
fi

# ─── 4. Update .env settings ─────────────────────────────────
log "[4/9] Updating .env configuration..."

if [ ! -f "$ENV_FILE" ]; then
  log "   ⚠️  .env not found at $ENV_FILE — checking alternate locations"
  ENV_FILE=$(find /opt /root /home -name '.env' 2>/dev/null | grep wantokjobs | head -1)
  log "   Found: $ENV_FILE"
fi

if [ -f "$ENV_FILE" ]; then
  # Set EMAIL_MODE=live
  if grep -q "^EMAIL_MODE=" "$ENV_FILE"; then
    sed -i "s/^EMAIL_MODE=.*/EMAIL_MODE=live/" "$ENV_FILE"
  else
    echo "EMAIL_MODE=live" >> "$ENV_FILE"
  fi
  log "   ✅ EMAIL_MODE=live set"

  # Set ADMIN_CRON_TOKEN
  CRON_TOKEN="d0823829e229ce8f5da1f2b0b257529eaabd8e7e710cc901c4c5e371026795e8"
  if grep -q "^ADMIN_CRON_TOKEN=" "$ENV_FILE"; then
    sed -i "s/^ADMIN_CRON_TOKEN=.*/ADMIN_CRON_TOKEN=$CRON_TOKEN/" "$ENV_FILE"
  else
    echo "ADMIN_CRON_TOKEN=$CRON_TOKEN" >> "$ENV_FILE"
  fi
  log "   ✅ ADMIN_CRON_TOKEN set"

  log "   ⚠️  GOOGLE_AI_KEY and bank details still need manual input (see below)"
else
  log "   ❌ .env file not found — skipping env updates"
fi

# ─── 5. Rebuild native modules ───────────────────────────────
log "[5/9] Rebuilding native Node.js modules..."
cd "$APP_DIR"
npm install --production 2>&1 | tail -5 | tee -a "$LOG"
npm rebuild better-sqlite3 2>&1 | tee -a "$LOG" || {
  log "   ⚠️  rebuild failed — trying clean install"
  rm -rf node_modules/better-sqlite3
  npm install better-sqlite3 --build-from-source 2>&1 | tee -a "$LOG"
}
log "   ✅ Native modules ready"

# ─── 6. Run database migrations ──────────────────────────────
log "[6/9] Running database migrations..."
node server/migrations/runner.js 2>&1 | tee -a "$LOG" && log "   ✅ Migrations complete" || log "   ⚠️  Migration issues — check log"

# ─── 7. Install cron jobs ─────────────────────────────────────
log "[7/9] Installing cron jobs..."
if [ -f "$APP_DIR/system/setup-crontab.sh" ]; then
  bash "$APP_DIR/system/setup-crontab.sh" 2>&1 | tee -a "$LOG"
  log "   ✅ Cron jobs installed"
else
  log "   ⚠️  setup-crontab.sh not found — adding minimal crontab"
  (crontab -l 2>/dev/null; echo "*/5 * * * * bash $APP_DIR/vps-scripts/watchdog.sh >> /var/log/wantokjobs-watchdog.log 2>&1") | crontab -
  log "   ✅ Watchdog cron added"
fi

# ─── 8. Apply nginx config ───────────────────────────────────
log "[8/9] Applying Nginx configuration..."
if [ -f "$APP_DIR/vps-scripts/nginx-tolarai.conf" ]; then
  cp "$APP_DIR/vps-scripts/nginx-tolarai.conf" /etc/nginx/sites-available/wantokjobs
  ln -sf /etc/nginx/sites-available/wantokjobs /etc/nginx/sites-enabled/wantokjobs
  if nginx -t 2>&1 | tee -a "$LOG"; then
    nginx -s reload
    log "   ✅ Nginx config applied and reloaded"
  else
    log "   ⚠️  Nginx config test failed — kept old config"
    rm -f /etc/nginx/sites-available/wantokjobs
  fi
else
  log "   ℹ️  Nginx config not found — skipping"
fi

# ─── 9. Restart service + health check ───────────────────────
log "[9/9] Restarting WantokJobs service..."
systemctl restart wantokjobs 2>&1 | tee -a "$LOG"
sleep 5

if systemctl is-active --quiet wantokjobs; then
  log "   ✅ Service is running"
else
  log "   ❌ Service failed to start — check: journalctl -u wantokjobs -n 50"
fi

# Health check
if curl -sf http://localhost:3001/health > /dev/null 2>&1; then
  log "   ✅ Health check passed"
else
  log "   ⚠️  Health check failed — service may still be starting"
fi

# ─── Summary ─────────────────────────────────────────────────
log ""
log "============================================================"
log " SETUP COMPLETE"
log "============================================================"
log " ✅ SSH key added for agent-zero access"
log " ✅ Code pulled: $(cd $APP_DIR && git log --oneline -1)"
log " ✅ jean-whatsapp service disabled"
log " ✅ EMAIL_MODE=live"
log " ✅ ADMIN_CRON_TOKEN set"
log " ✅ Native modules rebuilt"
log " ✅ Migrations run"
log " ✅ Cron jobs installed"
log " ✅ Nginx updated"
log " ✅ Service restarted"
log ""
log " ⚠️  STILL NEEDS MANUAL INPUT:"
log "    1. GOOGLE_AI_KEY= (get from aistudio.google.com — free)"
log "    2. Bank account details in server/utils/jean/sme-pricing.js"
log "    3. Verify real WhatsApp token/phone ID in .env"
log ""
log " Log file: $LOG"
log "============================================================"
