server {
    listen 80;
    server_name $1;
    root $2/client/dist;
    index index.html;
    location /api/ {
        proxy_pass http://localhost:$3/api/;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
    access_log /var/log/nginx/${1}_access.log;
    error_log /var/log/nginx/${1}_error.log;
}
